### PR TITLE
Prevent schedule_visit_suggesting from throwing an error when no points are imported because they are already known

### PR DESCRIPTION
**Pull request by saschazepter**
…ts are imported because they are already known

### CODE REVIEW

**Comment by Freika** [comment]
@saschazepter would you mind adding tests as well?

**Comment by saschazepter** [comment]
> @saschazepter would you mind adding tests as well?

Tested all my patches/pull request with my "live" installation. How do you wish tests to be documented?

For this case, you simply import a GPX file and import it a second time later on, where all points have already been imported the first time. So you will get the "strange" notification behaviour.
I have mapped the patched file into the docker containers for testing and retested it with the same GPX file.

**Comment by saschazepter** [comment]
OK ... got you. :-)

**Comment by Freika** [comment]
Just in case, here is the file you can add tests to :) https://github.com/Freika/dawarich/blob/master/spec/services/google_maps/records_parser_spec.rb

**Pull request closed without merging**
