### PR TITLE
Reset z-index on leaflet map

### PR DESCRIPTION
**Pull request by poldixd**
The dropdown is behind the leaflet map. You have to reset the z-index on the map to 0.

Before:
Screenshot 2024-12-01 135122

After:
Screenshot 2024-12-01 135217

### CODE REVIEW

**Comment by poldixd** [comment]
How can I recompile the assets? I'm not a rails developer 🫤

**Comment by poldixd** [comment]
Thank you. When I run `bin/rails tailwindcss:build` or `bin/rails tailwindcss:watch`, it results in many changes in the `app/assets/builds/tailwind.css`.

**Comment by Freika** [comment]
> Thank you. When I run `bin/rails tailwindcss:build` or `bin/rails tailwindcss:watch`, it results in many changes in the `app/assets/builds/tailwind.css`.

it's the expected behaviour

**Comment by Freika** [comment]
@poldixd is it ready to merge? :)

**Comment by poldixd** [comment]
Yes. You can merge it.

**Review by Freika — APPROVED** [review]
Thanks for the fix!

**Pull request merged**
