### PR TITLE
Add use_https option to photon call to fix Issue #333

### PR DESCRIPTION
**Pull request by chrisl8**
This is my first stab at fixing Issue #333 by adding configuration for the `use_https` variable to the Geocoder call, which was not required before when `https` was the only option.

I added a new `PHOTON_API_USE_HTTPS` environment variable, but defaulted it to `true` so that the default behavior is to mimic the previous behavior.

Setting `PHOTON_API_USE_HTTPS` to `false` should allow using photon without `https`.

Please test this.

Also if this works the docs should be updated, which I haven't done yet.

### CODE REVIEW

**Review by Freika — APPROVED** [review]
🔥

**Comment by Freika** [comment]
@chrisl8 you did it right the `'true'`, second argument to `ENV.fetch('PHOTON_API_USE_HTTPS', 'true')`, is the default value to be used in case env var is not found.

**Comment by cpetzel** [comment]
Can we add `PHOTON_API_USE_HTTPS` to the `environment variables` documentation? 
I burned a lot of time trying to get this to work, until I found this issue.

**Comment by Freika** [comment]
@cpetzel will add!

**Pull request merged**
